name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  app: required_env_fetcher-ruby
  branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}

jobs:
  lint:
    name: Lint (Ruby ${{ matrix.ruby }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # We only care about rubocop against the latest ruby
        ruby: ['3.4.4']

    steps:
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: latest
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop

  test:
    name: Test against (${{ matrix.ruby }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2.8', '3.3.8', '3.4.4']

    steps:
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: latest
          bundler-cache: true

      - name: bundle
        run: bundle

      - name: rspec
        run: bundle exec rspec --format RspecJunitFormatter --format progress
